# POST http://localhost:4000/api/v1/register
# Content-Type: application/json

# {
#   "name": "alghany",
#   "email": "alghany@gmail.com",
#   "password": "123123123",
#   "confirmPassword": "123123123"
# }

# POST http://localhost:4000/api/v1/login
# Content-Type: application/json

# {
#   "email": "alghany@gmail.com",
#   "password": "123123123"
# }

# GET http://localhost:4000/api/v1/logout

POST http://localhost:4000/api/v1//2fa/generate
